library(MASS)
library(ranger)
library(tree.interpreter)

set.seed(42L)
data(Boston)
rf <- ranger(medv ~ ., Boston)
rfNodeSize <- annotateNodeSize(rf, Boston[, -14])
str(rfNodeSize$forest$node.sizes)
class(rfNodeSize)
