# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

featureContribTreeCpp <- function(tidyRF, tree, X) {
    .Call('_tree_interpreter_featureContribTreeCpp', PACKAGE = 'tree.interpreter', tidyRF, tree, X)
}

trainsetBiasTreeCpp <- function(tidyRF, tree) {
    .Call('_tree_interpreter_trainsetBiasTreeCpp', PACKAGE = 'tree.interpreter', tidyRF, tree)
}

tidyRFCpp_randomForest <- function(rfobj, trainX, trainY, inbag_counts_ensemble) {
    .Call('_tree_interpreter_tidyRFCpp_randomForest', PACKAGE = 'tree.interpreter', rfobj, trainX, trainY, inbag_counts_ensemble)
}

tidyRFCpp_ranger <- function(rfobj, trainX, trainY, inbag_counts_ensemble) {
    .Call('_tree_interpreter_tidyRFCpp_ranger', PACKAGE = 'tree.interpreter', rfobj, trainX, trainY, inbag_counts_ensemble)
}

