# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

annotateHierarchicalPredictionCpp_randomForest <- function(rf, oldX) {
    .Call('_tree_interpreter_annotateHierarchicalPredictionCpp_randomForest', PACKAGE = 'tree.interpreter', rf, oldX)
}

annotateHierarchicalPredictionCpp_ranger <- function(rf, oldX) {
    .Call('_tree_interpreter_annotateHierarchicalPredictionCpp_ranger', PACKAGE = 'tree.interpreter', rf, oldX)
}

