# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decomposedPredictionCpp <- function(delta_node_responses, testX) {
    .Call('_tree_interpreter_decomposedPredictionCpp', PACKAGE = 'tree.interpreter', delta_node_responses, testX)
}

deltaNodeResponseCpp_randomForest <- function(rf, trainX, trainY, inbag_counts) {
    .Call('_tree_interpreter_deltaNodeResponseCpp_randomForest', PACKAGE = 'tree.interpreter', rf, trainX, trainY, inbag_counts)
}

deltaNodeResponseCpp_ranger <- function(rf, trainX, trainY, inbag_counts_ensemble) {
    .Call('_tree_interpreter_deltaNodeResponseCpp_ranger', PACKAGE = 'tree.interpreter', rf, trainX, trainY, inbag_counts_ensemble)
}

